travis:
  secure:
    BINSTAR_TOKEN: ErZGmk426YpkMBBlinUkMLWJfdTpA/MHDWLVUJfdgy3vU2F5g0tt5MvTL5yEtR6AR+cMuUg9MpgNn8xC1I2G8+8JFEaj3MCuUAOa/VH6DrpXgQAIgLWBsjNqCXvCkxDAFEGj5VI/c84E9iNURlnCDjwsL1qclv6UqrgjTDS6wMoOFzXoS33Yp0JbtsaUskwjlgFtvdT/qaqoVkVB/wOjXKAKFE0vbDut746OIZTFrkMwkE7CYYIpQEm2u9xj2tucUlehCH63N+GMog/ZexJ7tNuuA88XpcJ0fvfjR4HIUpGdIyLnXk79OJ5Vzk6WH+3dwfz7pudtj8PKllfoWMXfHJA3kUCBJkVYGSA9YuAXxtNVpqP5kkkDux9pgjgW7C6n6JEz6blac4sqkYnRZQx7vvirxJQ5TupD4x6BWgsByD2dycAoacpkJepZpQotFcl9LwFWI6baUAc64mqGhy5YHKC8A3oyw8v63CjRvtLW8lSUjwQr/d4eW/+OgF4ei7EMOCeXdggdxurhsD32+AutpCchqOgoahtQrdiXMqCJ+O+NxnCyjfjjer0ohbCLYSktlKZVZ9sJaTP851uMyi6LLfcECogNMlxERp6xIBvpSLYHjqm7ojdqJOUZv/glus4d6+sqme78iNOVr1TvQxrLXzbgBh9q7XuButM873tdU5U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
