travis:
  secure:
    BINSTAR_TOKEN: LrPueXzN1n0DAk4c3lJ8vJFb94qUlRZFfoqHWu9vjCLVwrjPfZisbPvBmHpLr6vGHrXR4y6zdXJbuuKYp0bHnYuN0BVTUy0dDYRjVvi1De9HNr54cHespqUdKHkuTnZkF3F+0LQHv5KWLBb3fhG7QB9KnqUYNtkkeU2anEEpibwZW67VrVQ+epw/7yvOQEd/TnZeQjjF6z9LYBoLifu1tY1Im90oXmdKdqo9Mc5rzA9of+FWhwOi7PL/7NFi+qzad+TC1KlIY6aneowh4CDDKUKXOmYMbBRNN74Gm7UH68gwGgZxI7laSyx7tQjFD/FlCfE72oos+t6QIlWsTngT+o/BhoLh1TG0b+MBGqs15gBlS+zvOARpLX/XigNovdQ5k5qLGmZWdjoRsWUB8NF8hcPqNywXl8eoNxnp3yCWL7vLCU9E9BPo4k7TLWynR3XoDz+YDAtQEq5jlltu5eDPvhOA9cnEzKznlnCEHYbUQkFJvqCS6uIY32Mk5XH6PRrAA+488pD+rIBP5XKlSNt+JsI/JQmgDsNWTeY7Jg6TR2Mb32EzQcVe0ufK9UZ2roELF0HNIAVoWsmuZAmlJ/HCJGTsiVbpFmyAyQiJe+74eX8RULqlJll2tpyiUh5G+Hwhr0BRL+4+cAWuGJiQccP6Waz0W/mFK3zvLddQwWN6mws=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
